### ISSUE TITLE
Xwt.Toolkit.CurrentEngine.Type is dummy

### ISSUE THREAD

**Issue by ksigne** [mono/xwt#260]
I tried to get running toolkit info, but failed. Here is screenshots of what i'm doing: Xwt.Toolkit.CurrentEngine.Type is equal to 0 independently of ToolkitType i pass to Initialize method. It's works same in main loop.

![image](https://f.cloud.github.com/assets/5941429/1558950/1e236c34-4fb7-11e3-9d81-689af619dccb.png)

![image](https://f.cloud.github.com/assets/5941429/1558952/2bbc83b2-4fb7-11e3-8c1d-29e450edf62b.png)

**Comment by sevoku** [comment]
Yes, it seems to happen when the toolkit is loaded using Application.Initialize or a tape name (string). Its because ```Toolkit.Load(string fullTypeName, bool isGuest)``` does not set the private toolkitType member like it does ```Toolkit.Load (ToolkitType type)```.
I think the easiest solution would be to set it directly on initialization of every backend (I mean the backend should do it and not the Toolkit base).

**Comment by sevoku** [comment]
@slluis: does cc4327ee93f209d6606b4eab4f8b2e614231a1a6 fix this?

**Comment by slluis** [comment]
Yes, it does.
