### ISSUE TITLE
WPF TreeView problems

### ISSUE THREAD

**Issue by ksigne** [mono/xwt#261]
I've tried to do TreeStore refill inside of Window.Shown handler, as i've done in GTK, WinForms, Delphi and more...

Actually ItemContainerGenerator.ContainerFromItem returns null in this case and we have exception. This occurs only if i try to modify TreeView in handlers. I don't know if this is expected behaviour.

**Comment by sevoku** [comment]
@DavidKarlas: any update on this?

**Comment by DavidKarlas** [comment]
"Virtual mode"/"Lazy loading" and selecting from code doesn't play nice in WPF... There are many discussions on internet trying to solve this but none has 100% solution... I think someone should take deep dive into WPF and this loading/generating of items...

However... I think this bug is probably solved by https://github.com/mono/xwt/pull/455 but I'm not 100%...

**Comment by sevoku** [comment]
I'd propose to merge #455 and to close this one. If someone finds a problem with this, a new issue should be opened.
