### ISSUE TITLE
TextEntry with icons

### ISSUE THREAD

**Issue by sevoku** [mono/xwt#478]
I would like to implement icons in TextEntry, like it is done in Gtk (primary/secondary icons). So basically a SearchTextBox but with customizable icons for any purpose (not only search). The backend implementations are pretty simple to do, but need on Wpf and Mac custom native widgets (e.g on Wpf a custom Xaml based TextBox derivate, I've already implemented. On Mac it would be a NSTextField with a slightly extended NSView).
So what I'd like to ask/discuss is the API and the way the backend classes should work. There are two ways:

1. simply add the icon properties (LeftIcon, RightIcon) to TextBox. The downside would be that the backends would always use the custom native TextBox widgets, even for the TextBox without icons by simply hiding them.
2. Add a new TextIconBox (hhm, some better name maybe?) derived from TextBox. On the backend side there would be derivates too (ExTextIconBox : ExTextBox in Wpf, CustomTextIconField : CustomTextField : NSTextField on Mac). It would require more code, but the original TextBox implementation would remain unchanged (so the backends).

What would be the right way to go?

**Comment by slluis** [comment]
I'd go with #2, but I don't think such a widget belongs to XWT. Icons in text entries is not an UI idiom common in all platforms.

**Comment by sevoku** [comment]
Hhm, why do you thinks so? Sure, such a (native) widget exists only in Gtk, but there are many apps that have similar (custom) widgets on different platforms (various browsers on win/mac/linux for example, even IE has icons in the address input, without wpf/winforms having this widget). Creating such a widget with Xwt only (without a native backend implementation) is not that easy for a user wanting this feature in an app (at least not if it should look really native on all platforms).
It's similar to a popover. Until Gtk3 I've never seen an app using something like a popover on Linux, and never on Windows, so its not a common idiom, too. But its part ow Xwt and it's pretty cool to have it for all platforms.
And I think many people would be happy to have icons in text entries, it's a good way to give the user a hint about the purpose of a text entry without the need of long tooltips or other descriptive ui elements.

**Comment by slluis** [comment]
One of the design goals of XWT is to provide a good native experience, and it should be done by offering widgets which have rich semantics that are rendered natively in each platform. For example, you said that icons would be a good way to give the user a hint about the purpose of an entry, so your conclusion is that it is useful to add support for icons in entries. But you are thinking about this backwards. If the goal is to provide usage hints to the user, then we should add support for "usage hints" to text entry. In some platforms those usage hints will be rendered as an icon, in other platforms it may be rendered in a different way.

Another example: you said that you want to provide something like a "SearchTextBox but with customizable icons", which means you are assuming that a search box is an entry with an icon, but generally speaking, it is not. A SearchTextBox is a widget with very particular semantics and may be rendered completely different in different platforms.

So if some platforms use icons in entries, we should find out what are those used for, what are the semantics behind it, and then add the semantics to TextEntry or create a new widget with those semantics.

I'm aware that this design approach can make XWT less flexible. You'll have less "pieces" to combine and it may be harder to make the UI look exactly like you want, but that's the price to pay in order to have a real native experience.

**Comment by sevoku** [comment]
Ok, I understand your point. My thought was that everything "is already there" on the backend side (see  #475, too) except of Mac, so it would be just one more frontend widget.
What do you think about a separate Xwt.Extras project (I mean really a new project, not a project file inside Xwt), which could include such things? It would come with own Backends then (like Xwt.Extras.Wpf, Xwt.Extras.Gtk,...). I'll implement the iconified TextEntry for my projects and would like to share it. This could be a nice place to concentrate 3rd party widgets.

**Comment by slluis** [comment]
I have no objection for a Xwt.Extras.
