### ISSUE TITLE
Build break: NSStringAttributeKey does not exist

### ISSUE THREAD

**Issue by skrysmanski** [mono/xwt#514]
Commit ca15fd675b057bd536e2c766be4e4ff929eaa4ff broke Xwt.Mac (i.e. not XamMac) especially because `NSAttributedString` has been replaced at a lot of places with `NSStringAttributeKey` which the compiler can't find. Also `nfloat` definitions are missing in some files.

**Comment by sevoku** [comment]
Yes, it's really a breaking change!

**Comment by xajler** [comment]
It is actually not a breaking change, you need to have Xamarin.Mac 2 installed to build this one or any Mac related repository for mono, you can download it here https://forums.xamarin.com/discussion/42674/stable-service-release-xamarin-mac-2-0-1-bug-fixes-for-2-0-0#latest

**Comment by sevoku** [comment]
Well its a breaking change for MonoMac users with the Xwt.Mac backend. We need some workaround here (maybe an extension method like its done with Gtk2/3 differences). Or MonoMac support could be dropped completely, if it's not under active development anymore (the last update was mono/monomac@36508cffdd4ce29f6c6e87f7c30d621d3cc512f3 on 19 Feb 15, so if XamarinMac is its official successor then this was the last OSS version of MonoMac?)

**Comment by skrysmanski** [comment]
@xajler I don't have Xamarin.Mac installed (nor do I want to start the trial just to find out), so could you tell me in which assembly `NSStringAttributeKey` is defined in? Xamarin.Mac? If so, we need a workaround because Xamarin.Mac isn't referenced (nor should it IMHO) by Xwt.Mac.

@sevoku I hope MonoMac support isn't dropped as this would be bad for open source developers.

**Comment by xajler** [comment]
@skrysmanski I think is all due to changes in Xamarin Studio and driven by Xamarin. To be honest I have no clue what is Xwt.Mac is, all I wanted is to compile MonoDevelop for which I haven't find any binaries, it seems is now only Xamarin Studio. 
MonoDevelop and Xamarin Studio seems have dependency on Xwt.Mac, it was breaking on this ``NSStringAttributeKey``, but I could compile when I've installed Xamrin.Mac. 
For what I've know you don't need to have any trial for Xamarin.Mac, because I don't have any subscription with Xamarin, and I had no problem to compile MonoDevolop and Xwt.Mac when I've installed this Xamarin Mac.

**Comment by sevoku** [comment]
You don't need a Xamarin.Mac license to compile MD, cause it is not checked when compiling libraries. Try running a Xamarin.Mac application and you'll get a message about a missing license. At the end you need a license when publishing your project so @skrysmanski is right.

I've merged #534, thanks!
closing here.
