### ISSUE TITLE
Gtk, Close request gets called twice when closing using the close button

### ISSUE THREAD

**Issue by cra0zy** [mono/xwt#530]
Close request gets called twice when closing using the close button in Gtk.

Example code for bug:
```c#
using Xwt;

public class MainWindow: Window
{
    public MainWindow()
    {
        this.Width = 640;
        this.Height = 480;

        this.CloseRequested += MainWindow_CloseRequested;
        this.Closed += (sender, e) => Application.Exit();
    }

    protected void MainWindow_CloseRequested (object sender, CloseRequestedEventArgs args)
    {
        MessageDialog.ShowMessage("Closing...");
    }
}
```

How to cause it?
Close the window.

**Comment by sevoku** [comment]
This is the normal behaviour with Gtk. Gtk has only the ```DeleteEvent``` which is similar to ```CloseRequested```. Since both Xwt events are called from inside an internal DeleteEvent handler (see https://github.com/mono/xwt/blob/master/Xwt.Gtk/Xwt.GtkBackend/WindowFrameBackend.cs#L314), the window is still not closed, when you receive the Closed event (look at MainWindow.Visible, its true). So calling ```Application.Exit``` triggers the same logic again.

One could say that this is a bug, but it isn't really one, cause ```CloseRequested``` should be used to control the closing action and should not depend on the Closed event. In other words, you should use only one of them. If you don't need any control, use Closed and if you want do add some checks use CloseRequested with ```CloseRequestedEventArgs.AllowClose```. 

Also take a look at: https://github.com/mono/xwt/blob/master/TestApps/Samples/MainWindow.cs#L156

**Comment by cra0zy** [comment]
@sevoku Oh... I didn't realize that. Thanks for clarification.
