### ISSUE TITLE
[Gtk3] Message dialogs are missing icon

### ISSUE THREAD

**Issue by cra0zy** [mono/xwt#597]
All the basic message dialogs in Gtk3 seem to be missing their respective icons:
![screenshot from 2016-05-23 08-11-55](https://cloud.githubusercontent.com/assets/6773302/15461783/10de1242-20be-11e6-85ce-cd52d5305e1f.png)

Gtk2 works fine.

**Comment by sevoku** [comment]
There are no message dialog icons in Gtk3 by design (I don't remember in which Gtk3 version they have been removed). They are still part of the api, but hidden (and afaik it can be reenabled by a theme or using some gconf flag...). Maybe they'll come back some day. For the message dialogs Xwt uses the native message api directly, so we have no full control over it. If you want to enforce the icons, you can build a custom dialog and arrange everything using tables, but it won't match the Gnome HIG anymore.

**Comment by cra0zy** [comment]
Ha, didn't realize it, sorry about this.
